#!/bin/bash
USAGE="
$0"' [--hide-window-after-prompt|-h] [--write-to-window|-w WRITE_WINDOW]
Prompts the user to select a common phrase and type it into `WRITE_WINDOW`.
Combines `i3h-select-common-phrase` and `i3h-type`.
If `hide-window-after-prompt` is set, hides the window after calling `3h-select-common-phrase`.
The `WRITE_WINDOW` is passed to `i3h-type`.'

# getopt
SHORT="h,w:"
LONG="hide-window,write-to-window:"
OPTS="$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")"
! [ "$?" = 0 ] && echo "$USAGE" 1>&2 && exit 1
eval set -- "$OPTS"

# Defaults
HIDE_WINDOW=0

# parses
while [[ "$#" -gt 0 ]]
do
    case "$1" in
        --hide-window|-h)
            HIDE_WINDOW=1
            shift
            ;;
        --write-to-window|-w)
            WRITE_TO_WINDOW="$2"
            shift
            shift
            ;;
        --)
            shift
            ;;
        *)
            echo "ERROR: INVALID ARGUMENTS" 1>&2
            echo "$USAGE" 1>&2
            exit 1;
            ;;
    esac
done

# Ensures args
if [ -z "$WRITE_TO_WINDOW" ]
then
    echo "ERROR: Missing WRITE_TO_WINDOW" 1>&2
    echo "$USAGE" 1>&2
    exit 1
fi

# Globals
TMPFILE=`mktemp`
trap 'rm -f "$TMPFILE"' EXIT

# Functions
function maybeHideWindow() {
    if [ "$HIDE_WINDOW" = "1" ]
    then
        i3-msg 'move scratchpad'
    fi
}

# Script
i3h-select-common-phrase 3>"$TMPFILE" && maybeHideWindow && i3h-type "$@" <"$TMPFILE"
