#!/bin/bash
USAGE="$0"' PHRASE
Send the keys on `PHRASE` to the currently focused windows, as if the user had
typed them.'

# Usage
if ! [ "$#" = "1" ]
then
    echo "ERROR: Expected exactly one argument" 1>&2
    echo "$USAGE" 1>&2
    exit 1
fi

# Capture variables
WINDOW="$(i3h-focused-window | jq '.window')"
PHRASE="$1"

# Script
sleep 0.5 && xdotool type --delay 75 --window "$WINDOW" "$PHRASE"
    
