#!/bin/bash -e

USAGE="\
USAGE:
  my-i3-move-workspaces-to-output <min_workspace_number> <output>
DESCRIPTION:
  Move all workspaces higher or equal than <min_workspace_number> to a specific <output>.
EXAMPLE:
  my-i3-move-workspaces-to-output 4 DP-1
"

[ ! "$#" = "2" ] && echo "$USAGE" 1>&2 && exit 1

MIN_WORKSPACE="$1"
TARGET_OUTPUT="$2"
WORKSPACES="$(i3-msg -t get_workspaces | jq '.[].num')"

while read i
do
    if [ "$i" -ge  "$MIN_WORKSPACE" ]
    then
        i3-msg "[workspace=$i] move workspace to output $TARGET_OUTPUT"
    fi
done < <(echo "$WORKSPACES")

