#!/bin/bash
USAGE="
$0"' [--hide-window-after-prompt|-h] -- ...args
Prompts the user to select a common phrase using `i3h-select-common-phrase` and pipes the
selected phrase to `i3h-type` stdin. `args` are given to i3h-type as-is.
If `hide-window-after-prompt` is set, hides the window after calling `i3h-select-common-phrase`.'

# getopt
SHORT="h"
LONG="hide-window,help"
OPTS="$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")"
! [ "$?" = 0 ] && echo "$USAGE" 1>&2 && exit 1
eval set -- "$OPTS"

# Defaults
HIDE_WINDOW=0

# parses
while [[ "$#" -gt 0 ]]
do
    case "$1" in
        --help)
            echo "$USAGE"
            exit 1
            ;;
        --hide-window|-h)
            HIDE_WINDOW=1
            shift
            ;;
        --)
            # Save "$@" for i3h-type
            shift
            break
            ;;
        *)
            echo "ERROR: INVALID ARGUMENTS" 1>&2
            echo "$USAGE" 1>&2
            exit 1;
            ;;
    esac
done

# Globals
TMPFILE=`mktemp`
trap 'rm -f "$TMPFILE"' EXIT

# Functions
function maybeHideWindow() {
    if [ "$HIDE_WINDOW" = "1" ]
    then
        i3-msg 'move scratchpad'
    fi
}

# Script
i3h-select-common-phrase 3>"$TMPFILE" && maybeHideWindow && i3h-type "$@" <"$TMPFILE"
